config/routes.rb
Rails.application.routes.draw do

  resources :admin
    
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :carts 
    resources :line_items
    resources :orders
    resources :users, except: :show
    resources :products do
      get :who_bought, on: :member
    end
    root 'store#index', as: 'store'
  end  

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  PAYMENT_TYPES = ["Check", "Credit Card", "Purchase Order" ]

  validates :name, :email, :address, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES

    after_touch do 
    puts "object has been touched"
  end

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_filter :authorize, only: [:new, :create]

  before_filter :current_cart
  
  def index
    @orders = Order.paginate(page: params[:page], per_page: 5)
                            .order('created_at desc')
    respond_to do |format|
      format.html 
      format.json { render json: @orders}
    end
  end

  def edit
    @order = Order.find(params[:id])
    respond_to do |format|
      format.html { redirect_to orders_path }
      format.js { @current_order = @order.id }
      end
  end

  def new
    @cart = current_cart
    if @cart.line_items.empty?
      redirect_to store_url, notice: "Your Cart is Empty. Please choose Items first and then proceed to checkout."
      return
    end
    @order = Order.new
    respond_to do |format|
      format.html
      format.json { render json: @order}
    end
  end

  def create
    @order = Order.new(order_params)
    @order.add_line_items_from_cart(current_cart)
    if @order.save
      Cart.destroy(session[:cart_id])
      OrderNotifier.received(@order).deliver
      session[:cart_id] = nil
      redirect_to store_url, notice: I18n.t('.thanks')
    else
      @cart = current_cart
      render action: 'new' 
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_path }
      format.js { @current_order = @order.id }
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Product was successfully updated.' }
        format.js { @updated_order = @order.id }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def order_params
    params.require(:order).permit(:name, :address, :email, :pay_type)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>
<%# byebug %>
    <% if @order.errors.any? %>
      <div id="error_explanation">
        <h2><%=raw t('errors.template.header', count: @order.errors.count,
                      model: t('activerecord.models.order')) %>.</h2>
            <p><%= t('errors.template.body') %></p>
        <ul>
          <% @order.errors.full_messages.each do |msg| %>
            <li><%=raw msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name, t('.name') %>
      <%= f.text_field :name, size: 40 %>
    </div>
    <div class="field">
      <%= f.label :address, t('.address_html') %>
      <%= f.text_area :address, rows: 3, cols: 40 %>
    </div>
    <div class="field">
      <%= f.label :email, t('.email') %>
      <%= f.email_field :email, size: 40 %>
    </div>
    <div class="field">
      <%= f.label :pay_type, t('.pay_type') %>
      <%= f.select :pay_type, Order::PAYMENT_TYPES, 
                    prompt: t('.prompt') %>
    </div>
    <div class="actions">
      <%= f.submit t('.submit') %>
    </div>

<% end %>

<div id="updated_order"></div>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.js.erb
$("#<%=@current_order %>").hide()

app/views/orders/edit.html.erb
<%= render partial: 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/edit.js.erb
$('#edit_form').html("<%= j render partial: 'form' %>")

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>  
  <tr class="list_header">
    <th>Name</th>
    <th>Address</th>
    <th>Email</th>
    <th>Pay type</th>
  </tr>

<% @orders.each do |order| %> 
    <tr class="table_row" id="<%=order.id%>">
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.email %></td>
        <td><%= order.pay_type %></td>
        <td class="list_actions">
          <td><%= link_to 'Show',  order_path(order.id) %></td>
          <td><%= link_to 'Edit', edit_order_path(order),  
                  remote: true %></td>
          <td><%= link_to 'Destroy', order_path(order) , method: :delete,
                  remote: true %></td>
        </td>
    </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>
<p><%= will_paginate @orders %></p>


<div id="edit_form"></div>

app/views/orders/new.html.erb
<div class="depot_form">
<fieldset>
<legend><%= t('.legend') %></legend>
  <%= render partial: 'form' %>
</fieldset>
</div>

app/views/orders/show.html.erb
<h3>Your Order is as </h3>
<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Email ID:</strong>
  <%= @order.email %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> 
<%= link_to 'Back', orders_path %>

app/views/orders/update.html.erb
<h3>Order has been edited </h3>
<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Email ID:</strong>
  <%= @order.email %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> 
<%= link_to 'Back', orders_path %>

<div id="updated_order"></div>

app/views/orders/update.js.erb
$('#updated_order').css({'background-color':'#88ff88'}).
  animate({'background-color':'#114411'}, 1000);