config/routes.rb
Rails.application.routes.draw do

  resources :admin
    
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :carts 
    resources :line_items
    resources :orders
    resources :users, except: :show
    resources :products do
      get :who_bought, on: :member
    end
    root 'store#index', as: 'store'
  end  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag "application", :media => "all" %> 
  <%= javascript_include_tag "application" %> 
  <%= csrf_meta_tags %>
</head>

<body>
<body class='<%= controller.controller_name %>'>
  <div id="banner">
    <%= form_tag store_path, method: :get, class: 'locale' do %>
      <%= select_tag 'set_locale', options_for_select(LANGUAGES, 
                      I18n.locale.to_s), onchange: 'this.form.submit()' %>
      <%= submit_tag "Submit" %>
      <%= javascript_tag "$(.locale input).hide()" %>
    <% end %>
    <%= image_tag("logo.jpg") %>
    <%= page_title %>  
  </div>

  <div id="columns">  
    <div id="side">
      <div id="cart">
        <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %> 
          <%= render @cart %>
        <% end %>
      </div>
      <ul>
          <h3><li><%= link_to t(".Home"), store_url %></li>
              <li><%= link_to t(".SignUP"), new_user_path, 
                      remote: true %></li>
              <li><%= link_to t(".SignIn"), login_path %></li></h3>
      </ul>

      <div id="create_user"></div>
      
      <% if session[:user_id] %>
        <ul>
          <li><%= link_to "Orders", orders_path %></li>
          <li><%= link_to "Products", products_path %></li>
          <li><%= link_to "Users", users_path %></li>
        </ul> 
        <%= link_to "Logout", logout_path , method: :delete %>
      <% end %> 
    </div>
    
    <div id="main">
      <%= yield %>
    </div>

  </div>
  <p>The time you visited this site was <%= Time.now %></p>
</body>
</html>